# Generated by Django 3.2.4 on 2024-01-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240115_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='https://i.ibb.co/pxsZbty/thin-line-suspect-person-icon-600nw-2154459203.webp', upload_to='', verbose_name='Images'),
        ),
    ]
