# Generated by Django 3.2.4 on 2024-01-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.ibb.co/pxsZbty/thin-line-suspect-person-icon-600nw-2154459203.webp', max_length=255, verbose_name='Images'),
        ),
    ]
