# Generated by Django 4.2 on 2024-01-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Comment text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('level', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=0)),
                ('tree_id', models.PositiveIntegerField(default=0)),
                ('karma', models.IntegerField(default=0)),
                ('file', models.ImageField(blank=True, null=True, upload_to='comment_files/', verbose_name='Attached comment file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.comment')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
