# Generated by Django 4.2 on 2024-01-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='home_page',
            field=models.URLField(blank=True, null=True, verbose_name='Home page'),
        ),
    ]
