# Generated by Django 4.2 on 2024-01-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='home_page',
        ),
    ]
